#include <stdio.h>
#include "encodings.h"

extern int example(int a, int b);
extern int addition(int a, int b);

int main(int argc, char** argv){
    
    // assuming that assembly source file is passed to this assembler as first argument
    // [<simple_assembler> source_file.asm -o ommition_file.*] * ->  format not yet decided
    const char* __assembler_name  = argv[0];
    const char* __assembly_source = argv[1];
    const char* __assembly_ommit  = argv[3];

    // read @__assembly_source and check for syntax error
    // convert instructions to bytecodes
    // write generated bytecodes to @__assembly_ommit
    printf("[READ ] : %-30s\n", __assembly_source);
    printf("[WRITE] : %-30s\n", __assembly_ommit );

    // Try getting an instruction and encoding it
    const int encoded = register_address("t3");
    printf("[ADDR ] : %d\n", encoded);

    return 0;
}